list: $/summer/dingtalk/models/dingtalktemplatemodel/columns.yaml
modelClass: Summer\Dingtalk\Models\DingtalkTemplateModel
title: DingtalkTemplate
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'summer/dingtalk/dingtalktemplate/update/:id'
